# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rdf-n3}
  s.version = "0.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gregg Kellogg"]
  s.date = %q{2011-07-10}
  s.description = %q{RDF::N3 is an Notation-3 and Turtle reader/writer for the RDF.rb library suite.}
  s.email = %q{gregg@kellogg-assoc.com}
  s.extra_rdoc_files = [
    "AUTHORS",
    "History.md",
    "README.md",
    "UNLICENSE",
    "VERSION"
  ]
  s.files = [
    ".yardopts",
    "AUTHORS",
    "History.md",
    "README",
    "README.md",
    "Rakefile",
    "UNLICENSE",
    "VERSION",
    "example-files/arnau-registered-vocab.rb",
    "example-files/arnau-stack-overflow.ttl",
    "example-files/best-buy.nt",
    "example-files/dwbutler-mj.n3",
    "example-files/dwbutler-mj.ttl",
    "example-files/lee-reilly-list.rb",
    "example-files/sp2b.n3",
    "example.rb",
    "lib/rdf/n3.rb",
    "lib/rdf/n3/format.rb",
    "lib/rdf/n3/patches/array_hacks.rb",
    "lib/rdf/n3/patches/graph_properties.rb",
    "lib/rdf/n3/reader.rb",
    "lib/rdf/n3/reader/bnf-rules.n3",
    "lib/rdf/n3/reader/meta.rb",
    "lib/rdf/n3/reader/n3-selectors.n3",
    "lib/rdf/n3/reader/n3.n3",
    "lib/rdf/n3/reader/parser.rb",
    "lib/rdf/n3/version.rb",
    "lib/rdf/n3/vocab.rb",
    "lib/rdf/n3/writer.rb",
    "rdf-n3.gemspec",
    "script/build_meta",
    "script/console",
    "script/parse",
    "script/tc",
    "script/yard-to-rubyforge",
    "spec/.gitignore",
    "spec/cwm_spec.rb",
    "spec/cwm_test.rb",
    "spec/format_spec.rb",
    "spec/matchers.rb",
    "spec/reader_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/swap_spec.rb",
    "spec/swap_test.rb",
    "spec/turtle_spec.rb",
    "spec/turtle_test.rb",
    "spec/writer_spec.rb"
  ]
  s.homepage = %q{http://github.com/gkellogg/rdf-n3}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{N3/Turtle reader/writer for RDF.rb.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rdf>, [">= 0.3.3"])
      s.add_development_dependency(%q<open-uri-cached>, [">= 0"])
      s.add_development_dependency(%q<spira>, [">= 0.0.12"])
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_development_dependency(%q<rdf-spec>, [">= 0.3.3"])
      s.add_development_dependency(%q<rdf-rdfxml>, [">= 0.3.3"])
      s.add_development_dependency(%q<rdf-isomorphic>, [">= 0.3.4"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rdf>, [">= 0.3.3"])
      s.add_dependency(%q<open-uri-cached>, [">= 0"])
      s.add_dependency(%q<spira>, [">= 0.0.12"])
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_dependency(%q<rdf-spec>, [">= 0.3.3"])
      s.add_dependency(%q<rdf-rdfxml>, [">= 0.3.3"])
      s.add_dependency(%q<rdf-isomorphic>, [">= 0.3.4"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdf>, [">= 0.3.3"])
    s.add_dependency(%q<open-uri-cached>, [">= 0"])
    s.add_dependency(%q<spira>, [">= 0.0.12"])
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
    s.add_dependency(%q<rdf-spec>, [">= 0.3.3"])
    s.add_dependency(%q<rdf-rdfxml>, [">= 0.3.3"])
    s.add_dependency(%q<rdf-isomorphic>, [">= 0.3.4"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

