# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rdf-n3}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gregg Kellogg"]
  s.date = %q{2010-06-03}
  s.description = %q{    RDF::N3 is an Notation-3 (n3-rdf) parser for Ruby using the RDF.rb library suite.
}
  s.email = %q{gregg@kellogg-assoc.com}
  s.extra_rdoc_files = [
    "AUTHORS",
     "History.txt",
     "README.rdoc"
  ]
  s.homepage = %q{http://github.com/gkellogg/rdf-rdfa}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Notation-3 (n3-rdf) and Turtle reader/writer for RDF.rb.}
  s.test_files = [
    "spec/cwm_spec.rb",
     "spec/n3reader_spec.rb",
     "spec/rdf_helper.rb",
     "spec/spec_helper.rb",
     "spec/swap_helper.rb",
     "spec/swap_spec.rb",
     "spec/triple_spec.rb",
     "spec/turtle_serializer_spec.rb",
     "spec/turtle_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rdf>, [">= 0.1.6"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdf-spec>, [">= 0"])
      s.add_development_dependency(%q<treetop>, [">= 1.4.0"])
    else
      s.add_dependency(%q<rdf>, [">= 0.1.6"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdf-spec>, [">= 0"])
      s.add_dependency(%q<treetop>, [">= 1.4.0"])
    end
  else
    s.add_dependency(%q<rdf>, [">= 0.1.6"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdf-spec>, [">= 0"])
    s.add_dependency(%q<treetop>, [">= 1.4.0"])
  end
end

