#!/usr/bin/env ruby -s
require 'rubygems'
$:.unshift(File.expand_path(File.join(File.dirname(__FILE__), "..", 'lib')))
require 'rdf/n3'
require 'rdf/ntriples'
require 'getoptlong'
require 'open-uri'

def run(input, base)
  reader_class = RDF::Reader.for($input_format.to_sym)
  writer_class = RDF::Writer.for($output_format.to_sym)
  raise "Reader not found for #{$input_format}" unless reader_class
  raise "Writer not found for #{$output_format}" unless writer_class

  start = Time.new
  num = 0
  if $parse_only
    include RDF::N3::Meta
    include RDF::N3::Parser
    puts "\nparse #{input.read}---\n\n" unless $quiet
    input.rewind
    if $quiet
      $stdout = StringIO.new
    end
    test(input, BRANCHES, REGEXPS)
    if $quiet
      $stdout = STDOUT
      print "."
    end
  elsif $output_format == :ntriples || $quiet
    reader_class.new(input, :base_uri => base, :strict => true).each do |statement|
      num += 1
      if $quiet
        #print "."
      else
        puts statement.to_ntriples
      end
    end
  elsif $output_format == :inspect
    reader_class.new(input, :base_uri => base, :strict => true).each do |statement|
      num += 1
      puts statement.inspect
    end
  else
    puts writer_class.buffer(:base_uri => base, :standard_prefixes => true) { |writer|
      reader_class.new(input, :base_uri => base, :strict => true).each do |statement|
        num += 1
        writer << statement
      end
    }
  end
  puts
  secs = Time.new - start
  puts "Parsed #{num} statements in #{secs} seconds @ #{num/secs} statements/second."
rescue
  fname = input.respond_to?(:path) ? input.path : "-stdin-"
  STDERR.puts("Error in #{fname}")
  raise
end

$verbose = false
$output_format = :ntriples
$input_format = :n3
base_uri  = "http://example.com"
input = nil

opts = GetoptLong.new(
  ["--debug", GetoptLong::NO_ARGUMENT],
  ["--verbose", GetoptLong::NO_ARGUMENT],
  ["--quiet", GetoptLong::NO_ARGUMENT],
  ["--format", GetoptLong::REQUIRED_ARGUMENT],
  ["--input-format", GetoptLong::REQUIRED_ARGUMENT],
  ["--execute", "-e", GetoptLong::REQUIRED_ARGUMENT],
  ["--parse-only", GetoptLong::NO_ARGUMENT],
  ["--uri", GetoptLong::REQUIRED_ARGUMENT]
)
opts.each do |opt, arg|
  case opt
  when '--verbose' then $verbose = true
  when '--quiet' then $quiet = true
  when '--debug' then ::RDF::N3::debug = true
  when '--execute' then input = arg
  when '--format' then $output_format = arg.to_sym
  when '--input-format' then $input_format = arg.to_sym
  when '--uri' then base_uri = arg
  when '--parse-only' then $parse_only = true
  end
end

if ARGV.empty?
  s = input ? input : $stdin.read
  run(StringIO.new(s), base_uri)
else
  ARGV.each do |test_file|
    run(Kernel.open(test_file), base_uri)
  end
end
puts